-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 10:59:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `idperfil` INT NOT NULL,
  `tag` INT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `idlogin` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `perfil_idperfil` INT NOT NULL,
  PRIMARY KEY (`idlogin`, `perfil_idperfil`),
  INDEX `fk_login_perfil1_idx` (`perfil_idperfil` ASC) VISIBLE,
  CONSTRAINT `fk_login_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `mydb`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cadastro` (
  `idcadastro` INT NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `datanasc` DATE NOT NULL,
  `login_idlogin` INT NOT NULL,
  PRIMARY KEY (`idcadastro`, `login_idlogin`),
  INDEX `fk_cadastro_login_idx` (`login_idlogin` ASC) VISIBLE,
  CONSTRAINT `fk_cadastro_login`
    FOREIGN KEY (`login_idlogin`)
    REFERENCES `mydb`.`login` (`idlogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receita` (
  `idreceita` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  `desc` VARCHAR(100) NOT NULL,
  `preparo` VARCHAR(355) NOT NULL,
  `ingredientes` VARCHAR(200) NOT NULL,
  `categoria` INT NOT NULL,
  PRIMARY KEY (`idreceita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idtipos` INT NOT NULL,
  `doce` INT NOT NULL,
  `salgado` INT NOT NULL,
  `bebidas` INT NOT NULL,
  `receita_idreceita` INT NOT NULL,
  PRIMARY KEY (`idtipos`, `receita_idreceita`),
  INDEX `fk_categoria_receita1_idx` (`receita_idreceita` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `mydb`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
